# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5677a1ff7b24f91f4c9649d7dfebe4e9b371b8eb0b4e3a4c27da449395a3f019f8b3caf207f2f8fa5d8c8bec3eeec54598f33f28c2b20711a445deb1e8d3f6db

test:
  secret_key_base: a273704e5d033223992945e01a859515d0187b4886d2e03a72bb8786e1086e271d9b471a7a3b1678de7dfe92dca0e410aece9239f2691db03782b1b34f646c2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
